apiVersion: v1
kind: Service
metadata:
  name: front-service-votingapp
  labels:
    name: front-service-votingapp
    type: frontend-service-vote
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  
  selector:
    name: voting-app
    type: frontend-vote
    app: demo-voting-app