apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    type: backend-service-postgres
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  
  selector:
    name: postgres
    type: backend-postgres
    app: demo-voting-app