apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    type: backend-redis
    app: demo-voting-app
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379
