apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    type: backend-service-redis
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  
  selector:
    name: redis
    type: backend-redis
    app: demo-voting-app