apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    name: result-app
    type: frontend-result
    app: demo-voting-app
spec:
  containers:
    - name: result-app-container
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
