apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: worker-app
    type: backend-worker
    app: demo-voting-app
spec:
  containers:
    - name: worker-app-container
      image: dockersamples/examplevotingapp_worker
